import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SplashCursor from "@/components/splash-cursor";
import BackgroundMusic from "@/components/music-player";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased border-border overflow-x-hidden bg-gradient-to-br from-[#b497bd] via-pink-50/30 to-white text-foreground min-h-screen`}
      >
        <SplashCursor />
        <BackgroundMusic />
        {children}
      </body>
    </html>
  );
}
